from config import BOT_NAME

BOT_NAME_TO_LOWER_CASE = BOT_NAME.lower()

EMA_WITH_TEXT = "@" + BOT_NAME_TO_LOWER_CASE
EMA_WITH_VOICE = "@v" + BOT_NAME_TO_LOWER_CASE
EMA_WITH_PHOTO = "@p" + BOT_NAME_TO_LOWER_CASE
EMA_WITH_IMAGE_VARIATION = "@i" + BOT_NAME_TO_LOWER_CASE
EMA_TRANSCRIBE_AUDIO = "@t" + BOT_NAME_TO_LOWER_CASE
EMA_HELP = "@h" + BOT_NAME_TO_LOWER_CASE